[project]
name = "peberanek-github-io"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "mkdocs-material~=9.6.14",
    "python-frontmatter>=1.1.0",
    "ruff>=0.14.10",
    "ty>=0.0.8",
]
